/**
 * 模組 04 專題事務發布與編輯的公開入口（母 spec §4.3）。票 15：建立、編輯、發布、發布更新；
 * 票 16：撤回、下架、重新發布、前台內容頁與日曆的截止。
 *
 * 跨模組只能從這裡引用，而且只能帶型別；執行期的實作由 composition 注入。
 */
export type {
  AudienceKind,
  CompetitionStatus,
  EditablePlacement,
  FieldType,
  FileRules,
  FormField,
  FormSchema,
  Invalid,
  ItemDraft,
  ItemFileKind,
  ItemInput,
  ItemStatus,
  ItemVisibility,
  Normalized,
  Placement,
  PublishCheck,
  PublishCheckKey,
  PublishState,
  ReceiverUnit,
  Viewer,
} from '@/application/items/items'
export {
  AUDIENCE_KINDS,
  AUDIENCE_LABEL,
  canViewItem,
  COLLECTION_AUDIENCES,
  collectsResponses,
  COMPETITION_CATEGORY,
  competitionStatus,
  describeDeadline,
  describeFailedChecks,
  EDITABLE_PLACEMENTS,
  EMPTY_COLLECTION_MESSAGE,
  failedChecks,
  FIELD_TYPE_LABEL,
  FIELD_TYPES,
  FILE_FIELD_MAX_MIB,
  INPUT_FIELD_TYPES,
  isAdmin,
  isInputField,
  isUuid,
  ITEM_STATUS_LABEL,
  ITEM_UPLOAD,
  MAX_ATTACHMENTS,
  MAX_FIELDS,
  normalizeField,
  normalizeItemInput,
  normalizeSchema,
  PLACEMENT_HINT,
  PLACEMENT_LABEL,
  publishChecks,
  RECEIVER_UNIT_LABEL,
  snapshotDueAt,
  SNAPSHOT_GRACE_MS,
  STATIC_FIELD_TYPES,
  studentCohortOf,
  SUBMISSION_FILE_TYPES,
  SUMMARY_MAX_LENGTH,
  TITLE_MAX_LENGTH,
} from '@/application/items/items'
export { plainTextToHtml, renderBodyHtml, sanitizeBody } from '@/application/items/rich-text'
export { describePublishReceipt, describeUpdateReceipt } from '@/application/items/receipts'
export type { LifecycleAction, LifecycleReceipt, LifecycleRefusal, PublicAccess } from '@/application/items/lifecycle'
export {
  describeLifecycleReceipt,
  describeRepublishExpired,
  LIFECYCLE_LABEL,
  LIFECYCLE_NEXT_STATUS,
  lifecycleCheck,
  publicAccessOf,
} from '@/application/items/lifecycle'
export type {
  EditorOptions,
  ItemCommand,
  ItemDetail,
  ItemFileSummary,
  ItemListRow,
  ItemQuery,
  ItemReview,
  MyDeadline,
  PublicItemCard,
  PublicItemPage,
  PublicItemQuery,
  PublicListFilter,
  PublishReceipt,
  RecipientGroup,
  RecipientPerson,
  RecipientPreview,
  RecipientQueryInput,
  ResponsePresence,
  SaveReceipt,
  StartItemUploadInput,
  UpdateChange,
  UpdateReceipt,
} from '@/application/items/ports'
