/**
 * 模組 01 帳號與權限的公開入口（母 spec §4.3）。
 *
 * 跨模組只能從這裡引用，而且只能帶型別；執行期的實作由 composition 注入。
 */
export type {
  AccountStatus,
  Actor,
  AnonymousActor,
  Capability,
  CohortMembership,
  ResolvedActor,
  Role,
} from '@/application/accounts/actor'
export { ANONYMOUS, canPerform, hasRole, statusGate } from '@/application/accounts/actor'
export type { ActorResolver } from '@/application/accounts/ports'
export type {
  ChangePasswordInput,
  ChangePasswordOutcome,
  SelfAccountCommand,
} from '@/application/accounts/self-account'
export type {
  CohortOption,
  CohortValueMatch,
  RosterAnalysis,
  RosterCommand,
  RosterCounts,
  RosterEntryDraft,
  RosterImportReceipt,
  RosterIssue,
  RosterIssueKind,
  RosterPreview,
  RosterUploadTicket,
  RosterVersionRow,
} from '@/application/accounts/roster'
export {
  analyzeRoster,
  normalizeName,
  pickCohort,
  ROSTER_MAX_BYTES,
  ROSTER_MAX_ROWS,
  rosterAccessDenied,
  rosterFileDownloadable,
  STUDENT_NO_PATTERN,
} from '@/application/accounts/roster'
export type {
  ApplicationFields,
  ApprovalDecision,
  CohortChoice,
  DecisionReceipt,
  DuplicateInfo,
  EmailComparison,
  EvidenceFlag,
  MyApplication,
  PendingApplication,
  PendingList,
  RateLimited,
  RegistrationCommand,
  RegistrationInput,
  RegistrationReceipt,
  RevisionReceipt,
  RosterCandidate,
  RosterHit,
  RosterMatch,
  RosterMatchStatus,
  TextComparison,
  VerificationMethod,
} from '@/application/accounts/registration'
export {
  APPLIED_NAME_MAX_LENGTH,
  DEPARTMENT_CLASS_MAX_LENGTH,
  EVIDENCE_LABEL,
  EVIDENCE_NEEDS_ATTENTION,
  evidenceFlags,
  matchRoster,
  normalizeApplicationFields,
  normalizeApproval,
  normalizeRegistrationInput,
  normalizeRejection,
  ownApplicationDenied,
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  REASON_MAX_LENGTH,
  resolveApprovalCohort,
  reviewAccessDenied,
  suggestedApprovalCohort,
  VERIFICATION_LABEL,
  VERIFICATION_METHODS,
  VERIFICATION_NOTE_HINT,
  VERIFICATION_NOTE_REQUIRED,
} from '@/application/accounts/registration'
export type {
  AccountCommand,
  AccountRow,
  AccountSummary,
  AdminRequestContext,
  BulkCandidate,
  BulkDisableReceipt,
  BulkLine,
  BulkPreview,
  BulkTarget,
  CohortFilterOption,
  DirectoryFilter,
  DirectoryPage,
  DirectorySort,
  DirectoryStatusFilter,
  ExportSelection,
  RevocationOutcome,
  SortDirection,
  StatusChange,
  StatusChangeReceipt,
} from '@/application/accounts/directory'
export {
  ACCOUNT_STATUS_LABEL,
  accountAdminDenied,
  BULK_MAX_CHARS,
  BULK_MAX_LINES,
  buildAccountsCsv,
  classifyBulk,
  DEFAULT_DIRECTORY_FILTER,
  DIRECTORY_PAGE_SIZE,
  DIRECTORY_ROLES,
  DIRECTORY_SORT_LABEL,
  DIRECTORY_SORTS,
  DIRECTORY_STATUSES,
  directoryQueryString,
  EXPORT_COLUMNS,
  EXPORT_MAX_ROWS,
  isUserId,
  likePattern,
  normalizeDirectoryFilter,
  normalizeExportSelection,
  normalizeStatusReason,
  parseBulkStudentNos,
  ROLE_LABEL,
  sameTargets,
  SEARCH_MAX_LENGTH,
} from '@/application/accounts/directory'
