/**
 * 模組 03 分組、指導與產學的公開入口（母 spec §4.3）。票 13：找組員、提案與成組；票 14：管理員調整組員與換組長；
 * 票 19：指導老師指派、認領與重派；票 20：產學合作案、組別連結、組長改類型、組別名單匯出。
 *
 * 跨模組只能從這裡引用，而且只能帶型別；執行期的實作由 composition 注入。
 */
export type {
  ConfirmReceipt,
  ExpireOutcome,
  GroupType,
  InvitationState,
  NormalizedProposal,
  ProposalState,
  ProposeInput,
  ProposeReceipt,
  SetOpenToJoinReceipt,
  TeammateListing,
  TerminateReceipt,
  TerminationKind,
} from '@/application/groups/proposals'
export {
  canViewTeammates,
  describeConfirmReceipt,
  describeTerminateReceipt,
  GROUP_TYPE_LABEL,
  GROUP_TYPES,
  INVITATION_STATE_LABEL,
  isAdmin,
  isUuid,
  nextGroupCode,
  normalizeProposeInput,
  normalizeVoidReason,
  PROPOSAL_STATE_LABEL,
  proposalExpiry,
  STUDENT_NO_MAX_LENGTH,
  studentCohortOf,
  TERMINATION_KIND_LABEL,
  VOID_REASON_MAX_LENGTH,
} from '@/application/groups/proposals'
export type {
  AddMemberInput,
  ChangeLeaderInput,
  LeaderChangeReceipt,
  MemberChangeReceipt,
  RemoveMemberInput,
} from '@/application/groups/members'
export {
  CHANGE_REASON_MAX_LENGTH,
  decideLeaderChange,
  decideRemoval,
  describeLeaderChangeReceipt,
  describeMemberChangeReceipt,
  groupSizeWarning,
  normalizeReason,
} from '@/application/groups/members'
export type {
  AdvisorBatchAnalysis,
  AdvisorBatchCounts,
  AdvisorBatchKind,
  AdvisorBatchOutcome,
  AdvisorBatchPreview,
  AdvisorBatchReceipt,
  AdvisorBatchRow,
  AdvisorBatchRowResult,
  AdvisorChangeKind,
  AdvisorChangeReceipt,
  AdvisorCsvFormatError,
  AdvisorInfo,
  AdvisorSource,
  AdvisorUploadTicket,
  AssignAdvisorInput,
  BatchGroupFact,
  BatchStep,
  BatchLookup,
  BatchTeacherFact,
  ClaimInput,
  ExecuteBatchInput,
  GradingAssignmentSummary,
  TeacherOption,
  UnassignAdvisorInput,
} from '@/application/groups/advisors'
export {
  ADVISOR_BATCH_KIND_LABEL,
  ADVISOR_BATCH_KINDS,
  ADVISOR_BATCH_OUTCOME_LABEL,
  ADVISOR_CSV_COLUMNS,
  ADVISOR_CSV_MAX_BYTES,
  ADVISOR_SOURCE_LABEL,
  analyzeAdvisorCsv,
  describeAdvisorBatchReceipt,
  describeAdvisorChangeReceipt,
  isBatchError,
  normalizeEmail,
  normalizeGroupCode,
  planBatch,
} from '@/application/groups/advisors'
export { describeGroupHistory } from '@/application/groups/history'
export type {
  ChangeGroupTypeInput,
  CreateOpportunityInput,
  GroupOpportunityLink,
  GroupTypeReceipt,
  LeaderTypeChangeFacts,
  LinkChange,
  LinkedGroupRef,
  LinkOpportunityInput,
  LinkReceipt,
  ManagedOpportunity,
  NormalizedOpportunity,
  NotesVisibility,
  OpportunityAction,
  OpportunityCard,
  OpportunityContact,
  OpportunityDetail,
  OpportunityField,
  OpportunityInput,
  OpportunityPage,
  OpportunityReceipt,
  OpportunityStatus,
  OpportunityStatusInput,
  UnlinkOpportunityInput,
  UpdateOpportunityInput,
} from '@/application/groups/opportunities'
export {
  canManageOpportunity,
  canViewOpportunities,
  describeGroupTypeReceipt,
  describeLinkReceipt,
  describeOpportunityReceipt,
  leaderTypeChangeBlockers,
  normalizeLinkReason,
  normalizeOpportunityInput,
  NOTES_VISIBILITY_LABEL,
  OPPORTUNITY_FIELD_LABEL,
  OPPORTUNITY_LIMITS,
  OPPORTUNITY_STATUS_LABEL,
  opportunityName,
  opportunitySummary,
  parseGroupType,
} from '@/application/groups/opportunities'
export type {
  RosterDirection,
  RosterExportFormat,
  RosterExportRequest,
  RosterFilter,
  RosterSort,
  RosterStatusFilter,
  RosterTypeFilter,
} from '@/application/groups/roster'
export {
  applyRosterFilter,
  buildRosterCsv,
  DEFAULT_ROSTER_FILTER,
  groupEmailList,
  normalizeRosterExportRequest,
  normalizeRosterFilter,
  ROSTER_EXPORT_COLUMNS,
  ROSTER_EXPORT_MAX_GROUPS,
  ROSTER_SEARCH_MAX_LENGTH,
  ROSTER_SORT_LABEL,
  ROSTER_SORTS,
  ROSTER_STATUS_FILTER_LABEL,
  ROSTER_STATUS_FILTERS,
  ROSTER_TYPE_FILTER_LABEL,
  ROSTER_TYPE_FILTERS,
  rosterExportRows,
  rosterQueryString,
} from '@/application/groups/roster'
export type {
  AdvisorCommand,
  AdvisorGradingLookup,
  CohortGroupingOverview,
  GroupHistoryEntry,
  GroupCommand,
  GroupMember,
  GroupQuery,
  GroupSummary,
  GroupRosterExporter,
  LeaderPanel,
  OpportunityCommand,
  OpportunityListFilter,
  OpportunityQuery,
  RosterExportResult,
  ProposalExpiryHandler,
  ProposalInvitation,
  ProposalSummary,
  StudentGroupView,
  UngroupedStudent,
} from '@/application/groups/ports'
